name       : libosinfo
version    : 1.6.0
release    : 8
source     :
    - https://gitlab.com/libosinfo/libosinfo/-/archive/v1.6.0/libosinfo-v1.6.0.tar.gz : 911238023b3aa5a17485d417a96978d16dae53e9edf488d27f3b9879289aec87
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : system.utils
summary    : The Operating System information database
description: |
    The goal of libosinfo is to provide a single place containing all the information about an operating system that is required in order to provision and manage it in a virtualized environment. It allows applications to
    - Query what hardware is supportable by an operating system
    - Query what hardware is supportable by a hypervisor
    - Determine the optimal hardware for running an operating system on a hypervisor
    - Find download location of installable ISO images and Live CDs
    - Find the location of online installation trees
    - Query the minimum/recommended/maximum CPU/memory/disk resources for an operating system
    - Automatically identify what operating system an ISO image is for
    - Generate scripts suitable for automating JEOS/Desktop installations
builddeps  :
    - pkgconfig(check)
    - pkgconfig(gobject-2.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libxml-2.0)
    - pkgconfig(libxslt)
    - vala
rundeps    :
    - osinfo-db
setup      : |
    %autogen --disable-static \
             --with-pci-ids-path=/usr/share/hwdata/pci.ids \
             --with-usb-ids-path=/usr/share/hwdata/usb.ids
    sed -i -e 's|GETTEXT_MACRO_VERSION = 0.19|GETTEXT_MACRO_VERSION = 0.20|' $workdir/po/Makefile.in.in
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
