name       : libosinfo
version    : 1.1.0
release    : 5
source     :
    - https://releases.pagure.org/libosinfo/libosinfo-1.1.0.tar.gz : 600f43a4a8dae5086a01a3d44bcac2092b5fa1695121289806d544fb287d3136
license    :
    - GPL-2.0-only
    - LGPL-2.1-only
component  : system.utils
summary    : The Operating System information database
description: |
    The goal of libosinfo is to provide a single place containing all the information about an operating system that is required in order to provision and manage it in a virtualized environment. It allows applications to
    - Query what hardware is supportable by an operating system
    - Query what hardware is supportable by a hypervisor
    - Determine the optimal hardware for running an operating system on a hypervisor
    - Find download location of installable ISO images and Live CDs
    - Find the location of online installation trees
    - Query the minimum/recommended/maximum CPU/memory/disk resources for an operating system
    - Automatically identify what operating system an ISO image is for
    - Generate scripts suitable for automating JEOS/Desktop installations
builddeps  :
    - pkgconfig(check)
    - pkgconfig(gobject-2.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libxml-2.0)
    - pkgconfig(libxslt)
    - vala
rundeps    :
    - osinfo-db
setup      : |
    %configure --disable-static \
               --with-usb-ids-path=/usr/share/hwdata/usb.ids \
               --with-pci-ids-path=/usr/share/hwdata/pci.ids
build      : |
    %make
install    : |
    %make_install
