name       : libosinfo
version    : 0.2.12
release    : 1
source     :
    - https://fedorahosted.org/releases/l/i/libosinfo/libosinfo-0.2.12.tar.gz : fa00ea8ddbca06c0dcc31e8938ac55cb71e71c6e2449687cd2c9e003a9478fed
license    :
    - GPL-2.0
    - LGPL-2.1
summary    : The Operating System information database
description: |
    The goal of libosinfo is to provide a single place containing all the information about an operating system that is required in order to provision and manage it in a virtualized environment. It allows applications to
    - Query what hardware is supportable by an operating system
    - Query what hardware is supportable by a hypervisor
    - Determine the optimal hardware for running an operating system on a hypervisor
    - Find download location of installable ISO images and Live CDs
    - Find the location of online installation trees
    - Query the minimum/recommended/maximum CPU/memory/disk resources for an operating system
    - Automatically identify what operating system an ISO image is for
    - Generate scripts suitable for automating JEOS/Desktop installations
builddeps  :
    - pkgconfig(gobject-2.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libxml-2.0)
    - pkgconfig(libxslt)
    - pkgconfig(check)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
