name       : libosinfo
version    : 1.7.1
release    : 9
source     :
    - https://gitlab.com/libosinfo/libosinfo/-/archive/v1.7.1/libosinfo-v1.7.1.tar.gz : 419bcba4543f8e6976abc643ee287ff69346591471cb368d444714a2777d25d2
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : system.utils
summary    : The Operating System information database
description: |
    The goal of libosinfo is to provide a single place containing all the information about an operating system that is required in order to provision and manage it in a virtualized environment.
builddeps  :
    - pkgconfig(check)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libxslt)
    - vala
rundeps    :
    - osinfo-db
setup      : |
    %meson_configure -Denable-gtk-doc=false \
        -Dwith-pci-ids-path=/usr/share/hwdata/pci.ids \
        -Dwith-usb-ids-path=/usr/share/hwdata/usb.ids
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
